CREATE TABLE ENDERECO(
	BAIRRO VARCHAR(60)
   ,RUA VARCHAR(60)
   ,TIPO_RES CHAR(2)
   ,NUM INT,
   ,CIDADE VARCHAR(40)
   ,UF CHAR(2)
   ,ID_CLIENTE
   ,FOREIGN KEY (ID_CLIENTE)
);

CREATE TABLE TELEFONE(
   
   ,
);